### ISSUE TITLE
[BE][Feedback Page][Add Feedback] User should be able to add feedback via a pop-up form that includes feedback type, subcategory, and description, with a toast message confirming the submission.

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-api#172]
**Description:**
When the user clicks on the "Add Feedback" button on the Feedback page, a pop-up should appear allowing the user to select the type of feedback and a subcategory. After selecting the feedback type and subcategory, the user should be able to provide a description of the feedback. Upon submitting the feedback, the user should see a toast message confirming that the feedback has been successfully submitted.

**Figma:**
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/9f4dbd6c-074b-4aee-8d4d-5aa6f55d82ed)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on the Feedback page,
When the user clicks on the "Add Feedback" button,
Then a pop-up should appear with options to select the type of feedback and a subcategory.

Acceptance Criteria 2:
Given the user is on the feedback pop-up,
When the user selects a type of feedback,
Then subcategories related to the selected feedback type should be displayed.

Acceptance Criteria 3:
Given the user has selected a feedback type and subcategory,
When the user is on the feedback pop-up,
Then the user should be able to provide a description of the feedback.

Acceptance Criteria 4:
Given the user has provided a description of the feedback,
When the user clicks on the "Submit" button,
Then the feedback should be submitted, and a toast message should appear confirming the submission.

**Comment by sanilnayak** [comment]
Tested the backend API and added bugs in the Excel sheet.
@shreyas070707 @ayushadhikari93  @nagesh953 closing the user story.
