### ISSUE TITLE
[BE][Feedback Page][Navigation and Display] User should be able to navigate to the Feedback page by clicking on the '?' button in the left-hand side panel. And user should see comprehensive UI of Feedback page 

### ISSUE THREAD

**Issue by Madhvan-0912** [sparrowapp-dev/sparrow-api#173]
**Description:**
When the user clicks on the '?' button in the left-hand side panel, they should be navigated to the Feedback page. The Feedback page should feature a tabs of Feedback and FAQs and an introduction to the page. Below the introduction, user feedback should be displayed. On the right-hand side (RHS) of the page, there should be a button for adding feedback and a box for joining the application's Discord channel, along with a button that redirects to the Discord channel as per figma.

**Figma:** 
![image](https://github.com/sparrowapp-dev/sparrow-app/assets/162560321/c65a9d26-7070-4bf0-b6f1-b45b7c875f8a)

**Acceptance Criteria:**

Acceptance Criteria 1:
Given the user is on any page of the application,
When the user clicks on the '?' button in the left-hand side panel,
Then the user should be navigated to the Feedback page.

Acceptance Criteria 2:
Given the user is on the Feedback page,
When the page loads,
Then the user should see a tab of Feedback and FAQs.

Acceptance Criteria 3:
Given the user is on the Feedback page,
When the page loads,
Then the user should see an introduction to the page below the header below which the user should able to see other users' feedback 

Acceptance Criteria 4:
Given the user is on the Feedback page,
When the page loads,
Then  the user should see a button on the right-hand side for adding feedback along with a box below this for joining the application's Discord channel by clicking on which user will be redirected to the discord channel.

**Comment by sanilnayak** [comment]
Tested the backend API and added bugs in the Excel sheet, closing the user story.
@shreyas070707 @ayushadhikari93 @nagesh953
