### ISSUE TITLE
"No result found" message is not implemented in workspace(member) search

### ISSUE THREAD

**Issue by shreyas070707** [sparrowapp-dev/sparrow-api#253]
Expected-
"No result message should present on UI
Actual-
![image](https://github.com/user-attachments/assets/a8129b51-cb20-452b-a27e-57a252ff990a)

**Comment by sanilnayak** [comment]
Resolved in MAC:

![Image](https://github.com/user-attachments/assets/6588745f-ea81-45d7-8dcd-89e8919bf5bb)

![Image](https://github.com/user-attachments/assets/caaf72c9-b0b1-4224-8905-3b71e9dcb3ff)

**Comment by satya1602** [comment]
Resolved in windows-

![Image](https://github.com/user-attachments/assets/6d84d2f7-9daa-4f81-83a0-c29ee65b10b7)


![Image](https://github.com/user-attachments/assets/5cf1278e-f7d9-4dfd-89ab-fb7f01d74c16)
